remote_theme: mmistakes/minimal-mistakes
title: "Nupur Nimbekar"
name: "Nupur Nimbekar"
description: "Robotics Software Engineer — Autonomy · Perception · ROS"
minimal_mistakes_skin: default
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
author:
  name: "Nupur Nimbekar"
  avatar: /assets/img/profile.jpg
  bio: "Robotics Software Engineer focusing on autonomy, perception, and planning for warehouse automation."
  location: "Boston Area, MA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ndnupur@terpmail.umd.edu"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/nimbekarnupur/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nimbekarnd"
collections:
  posts:
    output: true
permalink: /:categories/:title/
include:
  - _pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: true
      header:
        overlay_filter: 0.2
